server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: s3
    s3_sd_configs:
      - region: ap-south-1  
        bucket: www.krishchadha.online 
        role_arn: arn:aws:iam::123456789012:role/S3AccessRole  # Replace with your IAM role ARN
        access_key: YOUR_ACCESS_KEY  # Replace with your AWS access key
        secret_key: YOUR_SECRET_KEY  # Replace with your AWS secret key
        prefix: logs/  # Replace with your S3 prefix
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: message
            time: timestamp
      - labels:
          level:
          job: s3logs
